# Generated by Django 5.2.15 on 2026-06-25 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Porduct",
            new_name="Product",
        ),
    ]
